### ISSUE TITLE
Cannot read m4a file

### ISSUE THREAD

**Issue by Elikill58** [goxr3plus/java-stream-player#12]
Hello,

To use it, like my main project isn't a maven project, i have build a jar with dependencies (and it was difficult :( ).
So, i have a problem. I'm using audio file. Some of us are in mp3 and other of file are in m4a.
When i try to read m4a file, i get this error :
`juil. 25, 2019 6:37:10 PM com.goxr3plus.streamplayer.stream.StreamPlayer initAudioInputStream
INFOS: could not get audio input stream from input file
javax.sound.sampled.UnsupportedAudioFileException: could not get audio input stream from input file
	at javax.sound.sampled.AudioSystem.getAudioInputStream(Unknown Source)
	at com.goxr3plus.streamplayer.stream.StreamPlayer.initAudioInputStream(StreamPlayer.java:290)
	at com.goxr3plus.streamplayer.stream.StreamPlayer.open(StreamPlayer.java:264)`

Can you help me to fix it ?

**Comment by goxr3plus** [comment]
Well in the first place you should use Maven or Gradle, like that's how modern applications are build.

Maven is very easy to setup.


This librsry doesn't support m4a for the moment. But you can always covert them in.mp3 or wav using another library that i support which is

https://github.com/a-schild/jave2

We have ready examples and how you can add a progress listener so when it is 100 percent converted to play it :)

Let me know your progress.

**Comment by Elikill58** [comment]
Hello,

Thanks you, it's works !
I never find this lib to convert file, and it works, that fine !

**Comment by goxr3plus** [comment]
Of course it works its supported by me :)
