### ISSUE TITLE
Block main Thread

### ISSUE THREAD

**Issue by Elikill58** [goxr3plus/java-stream-player#13]
Hello,

I have open a new Issue because it's a different problem.
I have a JFrame, which contains button. When i click on the button, it play a sound.
The problem is, when i click on a button and i click a second time, it wait the end of the sound to replay it.
When i try to play only in a program (like "playSound(file) playSound(file)) it works.

Do you want some code ?

**Comment by goxr3plus** [comment]
There is a stop method in the Stream Player you can call it to immideately stop the player :)

**Comment by goxr3plus** [comment]
There are also pause and resume.

**Comment by Elikill58** [comment]
I want to play multiple sound at the same time !

**Comment by goxr3plus** [comment]
You can create two instances of Stream Player

**Comment by goxr3plus** [comment]
Stream Player actually uses a different thread to play the audio. Create two instances and call play eith the given file for them.

**Comment by Elikill58** [comment]
Yes, that just because i can't start the same sound two time at the same time. But, i have stop my projet now, maybe i will restart my projet soon.
