### ISSUE TITLE
Likely cause of split packages

### ISSUE THREAD

**Issue by HelgeStenstrom** [goxr3plus/java-stream-player#3]
https://github.com/goxr3plus/java-stream-player/blob/2f7d16dcf689a5335e91fe91bd6bfbdfe173cd6e/pom.xml#L100-L109

I think these two dependencies creates split packages, which in turn causes a runtime problem:

```text
Error:java: the unnamed module reads package org.tritonus.share.sampled.mixer from both tritonus.share and tritonus.all
```
in a program using Java 11 that has this repo as dependency.

Compare with this discussion: 
https://stackoverflow.com/questions/42358084/package-conflicts-with-automatic-modules-in-java-9

**Comment by goxr3plus** [comment]
Ouh yeah you are right, does tritonious all includes Tritonous share....?

If yes tritonous share is obsolete.

Please feel free to chnage fb e pom, check if it works and pull request. :)

**Comment by HelgeStenstrom** [comment]
It's not that easy for me to do. I have my library https://github.com/HelgeStenstrom/xr3UsageExamples where I try to define dependencies, import packages and do some very basic unit tests. I want it to depend on the same libraries as https://github.com/goxr3plus/XR3Player does, as far as I can. This problem is in one of the libraries that both xr3UsageExamples and XR3Player depend on. I don't want to maintain on my own fork of java-stream-player, create releases out of that, and depend on one of its releases. 

Having said that, I can at least tell that I have cloned java-stream-player, removed tritonus-share, and it doesn't seem to do any harm. Nothing is broken by that, as far as I could see.

**Comment by HelgeStenstrom** [comment]
Please help me with your Git knowledge. I cloned your library, and did changes on my computer. (removed tritonus-share, fixed the directory and package structure, removed a couple of files that shouldn't be there and put  TODO comment in Main). But I can't upload it from Github desktop, because I don't have permission.

My mistake was probably to clone your repo without forking it. Had I forked it, I think I would be able to make a pull request.

What can I do to share my changes with you? Can I fork the repo on my local machine, and then send it to Github? Have I described the problem enough?

**Comment by goxr3plus** [comment]
Look how it works, you fork the repository , clone it i to your local
machine, make any changes you want and then send pull request, i accept,
changes merged.

To avoid all this i can give you full permission on the repo and you can
directly clone into local machine and push, but are you responsible enough
you will not mess up things if i give you full permission :)?

**Comment by HelgeStenstrom** [comment]
So cloning someones else project on Github is a bad idea, unless you are sure that you only want to look around, and not make any changes, not even for yourself.

**Comment by HelgeStenstrom** [comment]
I have now forked and made some changes. But they are more for your inspiration, not for pull request. I have "fixed" the directory/package structure, but that will of course break code that use this library, so you cannot change that easily.

TonalidadeHidrica has found the same problem as me. He seems to know more than me how to fix it.

**Comment by goxr3plus** [comment]
@HelgeStenstrom No no no you just fork someone's repository and it's yours you can do whatever you want :)

**Comment by goxr3plus** [comment]
I saw the changes you made o  your latest commit, i like them, send me pull request.

One more think we don't need `. DStore` files, they are kind of file caching for Mac Pc :).

Add the file extension `. DStore` on gitignore and pull request.

It doesn't matter if we brake , it will be a new major version and i will explain thr changes.

**Comment by goxr3plus** [comment]
I have added you as a collaborator => https://github.com/goxr3plus/java-stream-player/invitations .

Please accept ,you don't have to pull request anymore , you can clone the repository and directly push to master :)

**Comment by TonalidadeHidrica** [comment]
Seems that @HelgeStenstrom and I encountered the same problem independently but simultaneously :) 

Anyway, as I mentioned [here](https://github.com/goxr3plus/java-stream-player/issues/6#issuecomment-487413691), depending to `soundlibs/tritonus-all` inevitably results in split packages. That's because `-all` requires `soundlibs/tritonus-share`, and those two distinct dependencies (which results in two jar files in modulepath, thus two automatic modules) has same packages in common.

In fact, `-share` is in all likelihood a subset of `-all`, so you can remove the dependency to `-share`.  Since we could not modify the original dependency (send a request to the repo?  It seems not to be developed more than 2.5 years, and we want to fix it NOW), one way to resolve it is manually excluding the transitive dependency to `-share`.  With Gradle script, you can do as follows:

```
compile group: 'com.github.goxr3plus', name: 'java-stream-player', version: '9.0.1' {
  exclude group: 'com.googlecode.soundlibs', module = 'tritonus-share'
}
```

Well, how to do in Maven?  I dunno 'cause I don't use Maven but maybe you can.  But why don't you use (rather) modern Gradle instead of Maven?  (I love modern stuff :)

**Comment by goxr3plus** [comment]
I will fork all the repos and make releases for all of them so we will not care, ;)

I will release all of em. :)

**Comment by goxr3plus** [comment]
With Maven you use <exclude>, ah you are right i should Use Gradle. Can you help me pass it in Gradle this project :)?

**Comment by goxr3plus** [comment]
I just considered more easy that's why :)

**Comment by TonalidadeHidrica** [comment]
Sure.  Currently `pom.xml` is not complex at all, so I can change it later.  The only wonder is if jitpack is available for publishing Gradle property.  I'll look for some information beforehand.

**Comment by goxr3plus** [comment]
I removed unused dependencies check latest version `9.0.2` and let me know if there are still problems .

@TonalidadeHidrica  @HelgeStenstrom

**Comment by TonalidadeHidrica** [comment]
It was still not working because of transitive dependency to `tritonus-share`, so I applied some fixes and made a pull request.  Now split packages are all resolved, I guess.
