### ISSUE TITLE
Wrong project name?

### ISSUE THREAD

**Issue by HelgeStenstrom** [goxr3plus/java-stream-player#4]
https://github.com/goxr3plus/java-stream-player/blob/2f7d16dcf689a5335e91fe91bd6bfbdfe173cd6e/.project#L3

You have a project that depends on both java-stream-player and on java-google-speech-api. You have a repository named java-google-speech-api. Then it looks suspect to have the name java-google-speech-api in this file.

**Comment by goxr3plus** [comment]
Oouuhh this was created by Eclipse, i shouldn't even upload this on the repository it ahould be deleted. Noe working with intelliJ we don't even need that kind of file. My mistake i should clean up a little bit.

**Comment by goxr3plus** [comment]
Can you please send me the link of that repository or open an issue there so i take action :) ?

**Comment by TonalidadeHidrica** [comment]
Maybe this issue is resolved (`.project` file no longer exists)?

**Comment by goxr3plus** [comment]
Yes i think so too :)
