### ISSUE TITLE
Prepare .gitignore for Jetbrain tools (IntelliJ)

### ISSUE THREAD

**Issue by HelgeStenstrom** [goxr3plus/java-stream-player#5]
I don't think you want to store IntelliJ project files in the git repo. It's a good idea to add to .gitignore

```text
# Jetbrains
.idea/
*.iml

# MacOS
.DS_Store
```

**Comment by goxr3plus** [comment]
Yes, adding on TODO.

**Comment by goxr3plus** [comment]
Done check latest release and commits :)
