### ISSUE TITLE
add module-info.java and rename jar file name

### ISSUE THREAD

**Issue by TonalidadeHidrica** [goxr3plus/java-stream-player#6]
Hi.  I found this project very useful.  Thanks for make them as a library.
By the way, I'm trying to use this library as a dependency but I encountered to a problem: I cannot use it from modular project (JDK >=9).  The current file name of jar file is `java-stream-player-V8.0.0.jar`, which results in an invalid automatic module name `java.stream.player.v8.0.0`.  So I have two proposals:

* Specify the module name by either
  * adding `module-info.java`, or
  * adding `Automatic-Module-Name` attribute into `MANIFEST.MF` file
* Renaming the jar file so that the module name would be valid.  The java compiler regards the last dot-separated sequence of integer after a hyphen of jar file name as the version number and use the rest as the module name, the jar file name `java-stream-player-8.0.0.jar` would be much better.

either of the above would work fine to avoid the error, but I suggest applying both because both are important convention.

**Comment by TonalidadeHidrica** [comment]
Tried all the approaches [by myself](https://github.com/TonalidadeHidrica/java-stream-player) and got following results:

* First, about the issue of automatic module name because of jar file name: jitpack seems to use tag name as version and the jar file name will be `{project_name}-{version_name}.jar`.  That's why the jar file name was `java-stream-player-v8.0.0.jar`, which is very unfriendly to Java 9 automatic module system.  One possible workaround is to use tag name without leading v's, such as `8.0.0`.  I confirmed that, with this way, the jar file name would be as expected. (cf. https://jitpack.io/#TonalidadeHidrica/java-stream-player)
* Since this project is [compiled with Java 8](https://github.com/TonalidadeHidrica/java-stream-player), it was not possible to add module-info.java .  (Is it for backward compatibility?)
* Adding `Automatic-Module-Name` worked well.  To do so, you can specify manifest attribute in `pom.xml` like [this](https://github.com/TonalidadeHidrica/java-stream-player/blob/master/pom.xml#L70).  With this approach I could successfully specify the dependency to this library.  
  * However, the entire build still failed because another dependency of this library [java-vorbis-support](https://github.com/trilarion/java-vorbis-support) uses same tagging strategy (`v1.0.0`).  Well, but don't worry, fortunately this library was published in [Maven Central Repository](https://mvnrepository.com/artifact/com.github.trilarion/vorbis-support/1.0.0).  
  * Now all the problem about automatic module name is resolved, but, here comes another problem - library `tritonus-share` and `tritonus-all` have several packages in common, such as `org.tritonus.share`.  Oh, how hard is it to use non-modular intended project from strict modular system!  Seems that it's still long way to use this library from my project.  I'm going to struggle further later.

**Comment by TonalidadeHidrica** [comment]
It seems that, from me, `tritonus-share` is a subset of `tritonus-all`, so excluding `tritonus-share` from dependency has been successful.  After adding excluding rule like this:

```gradle
    compile(group = "com.github.tonalidadehidrica", name = "java-stream-player", version = "8.0.4",
            dependencyConfiguration = {
                exclude(group="com.googlecode.soundlibs", module = "tritonus-share")
            })
```

I could finally play an audio!!!!!!! Horray!!!

By the way, my only concern is that the version of `tritonus-share` is 0.3.7.4, while that of `tritonus-all` is 0.3.7.2.  Would that cause problem?  Whatever, this is off-topic from this issue.

Anyway, again, please consider adding `Automatic-Module-Name` attribute and/or renaming version tags.  Thanks again for this awesome library.

**Comment by goxr3plus** [comment]
Do you want me to make you contributor on this project so you have direct access to commits :)?

I am not expert on Java 9 and above  trying to learn.

Do you want to be a contributor or send me pull requests which i will merge :)?

**Comment by goxr3plus** [comment]
We can change it all from the root if you want, i don't have a problem, we can make it be compatible only for Java 9 and above, after all Java 8 will be obsolete in some years :)

**Comment by goxr3plus** [comment]
I want to pass XR3Player in Java 11  and all this extra dependencies are making my passing difficult, let's change all of em.

**Comment by TonalidadeHidrica** [comment]
Wow, thanks for the invitation!  Actually I'm not sure I can contribute to this project continuously, so for now, let me send some pull request instead.  I'll send a pull req later before the changes in my repo was an experimental one.

**Comment by goxr3plus** [comment]
Latest version 9.0.1 works for you :) ?

**Comment by goxr3plus** [comment]
Be careful with your commits => https://github.com/goxr3plus/java-stream-player/invitations

Here is your collaborator invitation . Let me know before you do braking changes :)

**Comment by goxr3plus** [comment]
About your second section comment . I am reading and figuring out a solution .

**Comment by TonalidadeHidrica** [comment]
Thanks for the early action.  Now automatic module name problem for this project is resolved, but there's still problem of java-vorbis-support as I mentioned above.
What does  "second section" refer to?

**Comment by goxr3plus** [comment]
Second section refered to your second comment when you opened this issue.

**Comment by goxr3plus** [comment]
I contacted the owner of the 'java-vorbis-support' probably we  will remove that dependency, after all i am converting any piece of audio to. mp3 for now.

There is also and alternative called ![Image](https://i.imgur.com/2EDozCq.png)

**Comment by goxr3plus** [comment]
I have read the pom. xml of your project, working on it right now, it's just ah, if i remove borbis support then the library will support like literally only. mp3, which can be done also by default by JavaFX.

**Comment by TonalidadeHidrica** [comment]
I didn't remove vorbis support.  I found it was published in [Maven Central Repository](https://mvnrepository.com/artifact/com.github.trilarion/vorbis-support/1.0.0), so I just [substituted](https://github.com/TonalidadeHidrica/java-stream-player/blob/master/pom.xml#L108) it instead of using repo in jitpack.  The jitpack dependency causes `-v1.0.0.jar`, but Central Repo dependency doesn't, so it all worked well.

**Comment by goxr3plus** [comment]
I removed unused dependencies check latest version `9.0.2` and let me know if there are still problems .

@TonalidadeHidrica  @HelgeStenstrom
