### ISSUE TITLE
java-stream-player 10.0.0 is unresolvable

### ISSUE THREAD

**Issue by AObuchow** [goxr3plus/java-stream-player#63]
This might be a temporary issue (maybe something on jitpack.io's end) but I recently had to delete my maven `/.m2/repository/` and tried build my project which depends on java-stream-player 10.0.0 and it seems that it cannot be resolved.

```
[ERROR] Failed to execute goal on project sample-manager: Could not resolve dependencies for project com.aobuchow:sample-manager:jar:1.0-SNAPSHOT: Failed to collect dependencies at com.github.goxr3plus:java-stream-player:jar:10.0.0: Failed to read artifact descriptor for com.github.goxr3plus:java-stream-player:jar:10.0.0: Could not transfer artifact com.github.goxr3plus:java-stream-player:pom:10.0.0 from/to jitpack.io (https://jitpack.io): NullPointerException -> [Help 1]
```

https://jitpack.io/private#goxr3plus/java-stream-player/10.0.0 seems to look fine, however. Hopefully, this is just a temporary issue :)

**Comment by goxr3plus** [comment]
Hello Andrew this is strange indeed, can you try delete the repository again from m2 folder? This is probably a jit pack error.

**Comment by AObuchow** [comment]
@goxr3plus I deleted the .m2/repository folder again and tried but still get the same issue. However in

```
Downloading from jitpack.io: https://jitpack.io/com/github/goxr3plus/java-stream-player/10.0.0/java-stream-player-10.0.0.pom
[INFO] Failure detected.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10.315 s
[INFO] Finished at: 2020-06-23T08:17:42-04:00
[INFO] ------------------------------------------------------------------------
[WARNING] The requested profile "inject-application-home" could not be activated because it does not exist.
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.2-beta-5:single (default-cli) on project sample-manager: Failed to create assembly: Failed to resolve dependencies for project: com.aobuchow:sample-manager:jar:1.0-SNAPSHOT: Unable to get dependency information for com.github.goxr3plus:java-stream-player:jar:10.0.0: Failed to retrieve POM for com.github.goxr3plus:java-stream-player:jar:10.0.0: Failure to transfer com.github.goxr3plus:java-stream-player:pom:10.0.0 from https://jitpack.io was cached in the local repository, resolution will not be reattempted until the update interval of jitpack.io has elapsed or updates are forced. Original error: Could not transfer artifact com.github.goxr3plus:java-stream-player:pom:10.0.0 from/to jitpack.io (https://jitpack.io): NullPointerException
[ERROR]   com.github.goxr3plus:java-stream-player:jar:10.0.0
[ERROR] 
[ERROR] from the specified remote repositories:
[ERROR]   jitpack.io (https://jitpack.io, releases=true, snapshots=true),
[ERROR]   central (https://repo.maven.apache.org/maven2, releases=true, snapshots=false)
[ERROR] Path to dependency: 
[ERROR]         1) com.aobuchow:sample-manager:jar:1.0-SNAPSHOT
[ERROR] -> [Help 1]
```
I noticed `https://jitpack.io/com/github/goxr3plus/java-stream-player/10.0.0/java-stream-player-10.0.0.pom` seems to look fine in my browser. I'm going to see if there's something on my end. It's odd that 9.0.4 works for me however.

**Comment by goxr3plus** [comment]
Okay maybe it was because i was a pre-release , not sure ... i just release 10.0.1 
Also i am giving you full access to the repository in case you want to support and publish in Maven Central :) .

Please try 10.0.1 https://jitpack.io/private#goxr3plus/java-stream-player

**Comment by AObuchow** [comment]
> Okay maybe it was because i was a pre-release , not sure ... i just release 10.0.1
> Also i am giving you full access to the repository in case you want to support and publish in Maven Central :) .

Awesome thank you so much :) 

> Please try 10.0.1 https://jitpack.io/private#goxr3plus/java-stream-player

I still seem to be getting the same error but I'm going to investigate further on my end - I have a GitHub Actions CI setup for my project, I'll see if I get the same maven error on there.

**Comment by AObuchow** [comment]
So the build succeeded on GitHub Actions CI - this must be an issue on my end then. However, it's good you released 10.0.1 anyway as it has some of the new getDuration() API I added :) 

I'm going to close this issue since it seems to be that something's wrong with my local maven setup.

**Comment by goxr3plus** [comment]
Try also installing latest Maven or Gradle Version :)

**Comment by AObuchow** [comment]
Thanks for the suggestion @goxr3plus :) I had the latest version of Maven installed, but I was able to resolve my error by using Eclipse m2e's "Force update of snapshots/releases" option when doing "update project".

It's odd cause `mvn clean verify -U` is supposed to do the same but it didn't work either... oh well, at least now I can build my project locally :) 

Thank you so much for your help Alex!
