### ISSUE TITLE
Ability to change which mixer it plays to?

### ISSUE THREAD

**Issue by RinAndShizuka** [goxr3plus/java-stream-player#64]
I noticed the method getMixers() taunting me with no method to set which mixer it outputs to.
Is there a way to tell it which mixer to play to without simply setting that one as the default?

**Comment by goxr3plus** [comment]
That functionality is missing, any pull requests are welcome :)

**Comment by RinAndShizuka** [comment]
Not too familiar with github, I'll try my best to add my fix

**Comment by AObuchow** [comment]
Resolved via https://github.com/goxr3plus/java-stream-player/pull/65
