### ISSUE TITLE
Make StreamPlayer#reset public

### ISSUE THREAD

**Issue by TonalidadeHidrica** [goxr3plus/java-stream-player#7]
I looked for a way to freeing the resources opened by the StreamPlayer and found [StreamPlayer#reset](https://github.com/goxr3plus/java-stream-player/blob/master/src/main/java/goxr3plus/javastreamplayer/stream/StreamPlayer.java#L177) method, but it was private and was not accessible from outside.  Why is it private?  Is it possible to make it public?  (I also found that calling StreamPlayer#open method calls this reset method so it seems I don't have to worry so much as long as I used same StreamPlayer instance.)

**Comment by goxr3plus** [comment]
Calling the .stop() method will  free up all the resources, have a look at it :)

**Comment by goxr3plus** [comment]
Please try. stop() and let me know :)

**Comment by TonalidadeHidrica** [comment]
But stop() does not close file stream, audio output stream etc, right?  It seems that the only way to close them is calling reset().

**Comment by goxr3plus** [comment]
Please check the latest release :) https://github.com/goxr3plus/java-stream-player/releases 

9.0.1 solves exactly what you asked for :)
