### ISSUE TITLE
Update project JDK version to 11

### ISSUE THREAD

**Issue by TonalidadeHidrica** [goxr3plus/java-stream-player#8]
Current JDK version for this project is set to 1.8, according to `pom.xml`.  In order to make this project convenient in being used by other project which use module system introduced in JDK 9, module name should explicitly defined in `module-info.java`.  To accomplish it, the project JDK version will update to those no older than JDK 9, and actually, JDK 11, because [the main dependency of this project, XR3Player, will be developed in JDK 11](https://github.com/goxr3plus/java-stream-player/issues/6#issuecomment-487424469).

**Comment by TonalidadeHidrica** [comment]
Maybe there's a possibility that somebody (perhaps, not so many) who want to use this library is forced to use JDK >=11 ...?  I hope this change won't confuse those who already developed project with JDK 1.8, 9, or 10, or discourage people who don't want to use JDK >=11 ...

**Comment by TonalidadeHidrica** [comment]
I had second thought and realized that it's not a good choice to modularize this project yet.  This is because this project depends on some non-modularized library.  Requiring dependencies by automatic module name is, as far as I considered, not so good for such a public project like this.  I'll simply add `Automaic-Module-Name` attribute in the jar file instead.

**Comment by goxr3plus** [comment]
Yes go ahead, the scene is yours :)

**Comment by TonalidadeHidrica** [comment]
This will be deferred and closed for now
